version: '3'
services:
  eddi:
    image: labsai/eddi:latest
    ports:
      - "7070:7070"
      - "7443:7443"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      EDDI_VERSION: 4.7
      EDDI_ENV: production
      EDDI_MEMORY_MIN: 1G
      EDDI_MEMORY_MAX: 1G
      #EDDI_JAVA_ENV_MONGODB_HOST: mongodb.hosts=mongodb
  mongodb:
    image: mongo:3.6
    restart: always
