version: 2
branches:
  ignore:
    - gh-pages
jobs:
  build:
    docker:
      - image: labsai/ci-build
        environment:
          EDDI_ENV: development
          EDDI_JAVA_ENV_MONGODB_HOSTS: mongodb.hosts=eddi-storage-0.eddi-storage
    working_directory: ~/eddi
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          key: eddi
          paths:
            - /root/.m2

      - run: mvn clean package

      - run: mkdir -p $CIRCLE_TEST_REPORTS/junit/
      - run: find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;

      - save_cache:
          key: eddi
          paths:
            - /root/.m2

      - run:
         name: Start container and verify it's working
          command: |
            set -x
            chmod +x integration-tests.sh
            ./integration-tests.sh