version: 2
branches:
  ignore:
    - gh-pages
jobs:
  build:
    docker:
      - image: labsai/ci-build
    working_directory: ~/eddi
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          key: eddi
          paths:
            - /root/.m2

      - run: mvn clean package

      - run: mkdir -p $CIRCLE_TEST_REPORTS/junit/
      - run: find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;

      - save_cache:
          key: eddi
          paths:
            - /root/.m2

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            chmod +x integration-tests.sh
            ./integration-tests.sh

      - deploy:
          name: Build and push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker login -u $DOCKER_USER -p $DOCKER_PASS

            docker build --build-arg EDDI_VERSION=4.7 --build-arg EDDI_ENV=production -t labsai/eddi:4.7.0-b$CIRCLE_BUILD_NUM .
            docker push labsai/eddi:4.7.0-b$CIRCLE_BUILD_NUM

            docker build --build-arg EDDI_VERSION=4.7 --build-arg EDDI_ENV=production -t labsai/eddi:latest .
            docker push labsai/eddi:latest

            # docker build --build-arg EDDI_VERSION=4.7 --build-arg EDDI_ENV=production -t labsai/eddi:4.7.0 .
            # docker push labsai/eddi:4.7.0

            # docker build --build-arg EDDI_VERSION=4.7 --build-arg EDDI_ENV=production -t labsai/eddi:4.7 .
            # docker push labsai/eddi:4.7

            # docker build --build-arg EDDI_VERSION=4.7 --build-arg EDDI_ENV=production -t labsai/eddi:4 .
            # docker push labsai/eddi:4
            fi
